### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by vlasov01** [Comcast/prometheus-rpms-centos6#1]
Hi,

The installation steps in README.md should be adjusted to the recent release as URLs for the required files has been changed.
Here is the error log:
```
# rpm --import https://github.com/Comcast/prometheus-rpms-centos6/releases/download/0.0.1-65/RPM-GPG-KEY-comcast-xmidt
curl: (22) The requested URL returned error: 404 Not Found
error: https://github.com/Comcast/prometheus-rpms-centos6/releases/download/0.0.1-65/RPM-GPG-KEY-comcast-xmidt: import read failed(2).
```

Based on the current state it should be:
```
rpm --import https://github.com/Comcast/prometheus-rpms-centos6/releases/download/Release-7/RPM-GPG-KEY-comcast-xmidt
yum install https://github.com/Comcast/prometheus-rpms-centos6/releases/download/Release-7/node_exporter-0.15.1-7.el6.x86_64.rpm
```

**Comment by schmidtw** [comment]
@vlasov01 I'm not sure how I missed this issue for so long.  I adjusted the links so they're easier to use.  We have since moved on to Centos 7, so this is likely one of the last updates to this project.

**Comment by vlasov01** [comment]
@schmidtw Thank you!
